nameserver:
  replicaCount: 1
  image:
    repository: "apache/rocketmq"
    tag: "latest"
  port: 9876
  heapSize: "1792M"
  nodeSelector:
    fxiaoke.com/dedicated: middleware
  tolerations:
    - key: "fxiaoke.com/dedicated"
      operator: "Equal"
      value: "middleware"
      effect: "NoSchedule"
  persistence:
    enabled: false
    size: 8Gi
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi

proxy:
  replicaCount: 1
  image:
    repository: "apache/rocketmq"
    tag: "latest"
  heapSize: "1920M"
  maxDirectMemorySize: "384M"
  resources:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 2Gi
  nodeSelector:
    fxiaoke.com/dedicated: middleware
  tolerations:
    - key: "fxiaoke.com/dedicated"
      operator: "Equal"
      value: "middleware"
      effect: "NoSchedule"
broker:
  replicaCount: 3
  image:
    repository: "apache/rocketmq"
    tag: "latest"
  persistence:
    enabled: true
    size: 8Gi
  conf:
    heapSize: "3G"
  store:
    storageClass: "local-path"
    data:
      size: 10Gi
    log:
      size: 2Gi
  jvmMemory: " -Xms2g -Xmx2g -Xmn1g -XX:MaxDirectMemorySize=4g "
  resources:
    limits:
      cpu: 2000m
      memory: 12Gi
    requests:
      cpu: 200m
      memory: 4Gi
  nodeSelector:
    fxiaoke.com/dedicated: middleware
  tolerations:
    - key: "fxiaoke.com/dedicated"
      operator: "Equal"
      value: "middleware"
      effect: "NoSchedule"

controller:
  replicas: 3
  image:
    registry: docker.io
    repository: "apache/rocketmq"
    tag: "latest"
  resources:
    limits: 
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 2Gi
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path
  nodeSelector:
    fxiaoke.com/dedicated: middleware
  tolerations:
    - key: "fxiaoke.com/dedicated"
      operator: "Equal"
      value: "middleware"
      effect: "NoSchedule"
